import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { poppins } from "./fonts";
import { TRPCProvider } from "./_trpc/Provider";

export const metadata: Metadata = {
  title:{
    default: "DSS Project System",
    template: "%s | DSS Project System",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className)}>
        <TRPCProvider>
            {children}
        </TRPCProvider>
      </body>
    </html>
  );
}
