import { ChartConfig } from "@/components/ui/chart";
import { PageRoutes } from "@/constants/page-routes";
import {
  Building,
  CircleParking,
  ClipboardList,
  FileUser,
  LayoutDashboard,
  NotebookPen,
  StretchHorizontal,
} from "lucide-react";

export const items = [
  {
    title: "Dashboard",
    url: PageRoutes.DASHBOARD,
    icon: LayoutDashboard,
  },
  {
    title: "Rooms",
    url: PageRoutes.ROOMS,
    icon: Building,
  },
  {
    title: "Bookings",
    url: PageRoutes.BOOKINGS,
    icon: NotebookPen,
  },
  {
    title: "Guests",
    url: PageRoutes.GUEST,
    icon: FileUser,
  },
  {
    title: "Parkings",
    url: PageRoutes.PARKINGS,
    icon: CircleParking,
  },
];

export const housekeeping = [
  {
    title: "Tasks",
    url: PageRoutes.TASKS,
    icon: ClipboardList,
  },
  {
    title: "Inventory",
    url: PageRoutes.INVENTORY,
    icon: StretchHorizontal,
  },
];

export const chartConfig = {
  visitors: {
    label: "Visitors",
  },
  january: {
    label: "January",
    color: "hsl(var(--chart-1))",
  },
  february: {
    label: "February",
    color: "hsl(var(--chart-2))",
  },
  march: {
    label: "March",
    color: "hsl(var(--chart-3))",
  },
  april: {  
    label: "April",
    color: "hsl(var(--chart-4))",
  },
  may: {  
    label: "May",
    color: "hsl(var(--chart-5))",
  },
  june: {  
    label: "June",
    color: "hsl(var(--chart-6))",
  },
  other: {
    label: "Other",
    color: "hsl(var(--chart-7))",
  },
} satisfies ChartConfig;


//sample data
export const transactions = [
  {
    transaction_id: 1,
    guest_id: 101,
    room_id: 305,
    employee_id: 23,
    payment_method: "Credit Card",
    payment_amount: 150.0,
    payment_date: "2024-01-01",
    booking_type: "Online",
    check_in: "2024-01-01",
    check_out: "2024-11-05",
    additional_services: ["Breakfast", "Spa"],
    transaction_status: "Completed",
    total_days: 4,
  },
  {
    transaction_id: 2,
    guest_id: 102,
    room_id: 410,
    employee_id: 18,
    payment_method: "Cash",
    payment_amount: 200.0,
    payment_date: "2024-02-02",
    booking_type: "Walk-in",
    check_in: "2024-02-02",
    check_out: "2024-11-04",
    additional_services: ["Dinner", "Gym Access"],
    transaction_status: "Completed",
    total_days: 2,
  },
  {
    transaction_id: 3,
    guest_id: 103,
    room_id: 201,
    employee_id: 22,
    payment_method: "PayPal",
    payment_amount: 120.0,
    payment_date: "2024-03-03",
    booking_type: "Online",
    check_in: "2024-03-03",
    check_out: "2024-11-06",
    additional_services: ["Pool Access"],
    transaction_status: "Pending",
    total_days: 3,
  },
  {
    transaction_id: 4,
    guest_id: 104,
    room_id: 112,
    employee_id: 17,
    payment_method: "Debit Card",
    payment_amount: 175.0,
    payment_date: "2024-04-04",
    booking_type: "Online",
    check_in: "2024-04-04",
    check_out: "2024-11-08",
    additional_services: ["Breakfast", "Gym Access"],
    transaction_status: "Completed",
    total_days: 4,
  },
  {
    transaction_id: 5,
    guest_id: 105,
    room_id: 506,
    employee_id: 21,
    payment_method: "Credit Card",
    payment_amount: 300.0,
    payment_date: "2024-11-05",
    booking_type: "Walk-in",
    check_in: "2024-04-05",
    check_out: "2024-11-10",
    additional_services: ["Spa", "Dinner"],
    transaction_status: "Completed",
    total_days: 5,
  },
  {
    transaction_id: 6,
    guest_id: 106,
    room_id: 301,
    employee_id: 25,
    payment_method: "Cash",
    payment_amount: 90.0,
    payment_date: "2024-04-06",
    booking_type: "Online",
    check_in: "2024-05-06",
    check_out: "2024-11-07",
    additional_services: ["Breakfast"],
    transaction_status: "Cancelled",
    total_days: 1,
  },
  {
    transaction_id: 7,
    guest_id: 107,
    room_id: 320,
    employee_id: 19,
    payment_method: "Credit Card",
    payment_amount: 140.0,
    payment_date: "2024-11-07",
    booking_type: "Online",
    check_in: "2024-05-07",
    check_out: "2024-11-09",
    additional_services: ["Gym Access"],
    transaction_status: "Completed",
    total_days: 2,
  },
  {
    transaction_id: 8,
    guest_id: 108,
    room_id: 208,
    employee_id: 20,
    payment_method: "Credit Card",
    payment_amount: 180.0,
    payment_date: "2024-11-08",
    booking_type: "Walk-in",
    check_in: "2024-06-08",
    check_out: "2024-11-12",
    additional_services: ["Breakfast", "Spa", "Dinner"],
    transaction_status: "Completed",
    total_days: 4,
  },
  {
    transaction_id: 9,
    guest_id: 109,
    room_id: 415,
    employee_id: 16,
    payment_method: "PayPal",
    payment_amount: 250.0,
    payment_date: "2024-11-09",
    booking_type: "Online",
    check_in: "2024-11-09",
    check_out: "2024-11-13",
    additional_services: ["Gym Access", "Pool Access"],
    transaction_status: "Pending",
    total_days: 4,
  },
  {
    transaction_id: 10,
    guest_id: 110,
    room_id: 102,
    employee_id: 26,
    payment_method: "Debit Card",
    payment_amount: 220.0,
    payment_date: "2024-11-10",
    booking_type: "Walk-in",
    check_in: "2024-11-10",
    check_out: "2024-11-14",
    additional_services: ["Breakfast", "Dinner", "Spa"],
    transaction_status: "Completed",
    total_days: 4,
  },
];
